import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
// need to use dynamic import to prevent server-side rendering playroomkit functions. 'use client' not enough.
const Experience = dynamic(() => import("../components/Experience"), {
  ssr: false,
});
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen overflow-hidden`}>
        <Experience />
        {children}
      </body>
    </html>
  );
}
